import Head from "next/head";
import Image from "next/image";
import Toolbar from "@/components/Toolbar";
import SettingBar from "@/components/SettingBar";
import Canvas from "@/components/Canvas";
import s from '@/styles/Home.module.scss'

export default function Home() {
  return (
    <>
      <Head>
        <title>WS Paint</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={s.app}>
        <Toolbar />
        <SettingBar />
        <Canvas />
      </main>
    </>
  );
}
