import Head from "next/head";
import s from '@/styles/Home.module.scss'
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter()
  const handleClickRedirect = () => {
    router.push('/example')
  }
  return (
    <>
      <Head>
        <title>WebSocket Paint</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={s.app}>
        <div className={s.title}>Вас приветствует WebSocket Paint</div> <br />
        <div className={s.subtitle}>
          Функционал: <br />
          - онлайн холст на вебсокетах<br />
          - кисти любого цвета <br />
        </div>
        <button
          onClick={handleClickRedirect}
          className={s.btn}
        >
          открыть холст
        </button>
      </main>
    </>
  );
}
